/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_uwaterloo_jcltune_JTuner */

#ifndef _Included_ca_uwaterloo_jcltune_JTuner
#define _Included_ca_uwaterloo_jcltune_JTuner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ca_uwaterloo_jcltune_JTuner
 * Method:    init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_jcltune_JTuner_init
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     ca_uwaterloo_jcltune_JTuner
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_jcltune_JTuner_dispose
  (JNIEnv *, jobject);

/*
 * Class:     ca_uwaterloo_jcltune_JTuner
 * Method:    addKernel
 * Signature: (Ljava/util/List;Ljava/lang/String;[I[I)I
 */
JNIEXPORT jint JNICALL Java_ca_uwaterloo_jcltune_JTuner_addKernel
  (JNIEnv *, jobject, jobject, jstring, jintArray, jintArray);

/*
 * Class:     ca_uwaterloo_jcltune_JTuner
 * Method:    addKernelFromString
 * Signature: (Ljava/lang/String;Ljava/lang/String;[I[I)I
 */
JNIEXPORT jint JNICALL Java_ca_uwaterloo_jcltune_JTuner_addKernelFromString
  (JNIEnv *, jobject, jstring, jstring, jintArray, jintArray);

/*
 * Class:     ca_uwaterloo_jcltune_JTuner
 * Method:    setReference
 * Signature: (Ljava/util/List;Ljava/lang/String;[I[I)V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_jcltune_JTuner_setReference
  (JNIEnv *, jobject, jobject, jstring, jintArray, jintArray);

/*
 * Class:     ca_uwaterloo_jcltune_JTuner
 * Method:    setReferenceFromString
 * Signature: (Ljava/lang/String;Ljava/lang/String;[J[J)V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_jcltune_JTuner_setReferenceFromString
  (JNIEnv *, jobject, jstring, jstring, jlongArray, jlongArray);

/*
 * Class:     ca_uwaterloo_jcltune_JTuner
 * Method:    addParameter
 * Signature: (ILjava/lang/String;[I)V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_jcltune_JTuner_addParameter
  (JNIEnv *, jobject, jint, jstring, jintArray);

/*
 * Class:     ca_uwaterloo_jcltune_JTuner
 * Method:    addParameterReference
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_jcltune_JTuner_addParameterReference
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     ca_uwaterloo_jcltune_JTuner
 * Method:    mulGlobalSize
 * Signature: (I[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_jcltune_JTuner_mulGlobalSize
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     ca_uwaterloo_jcltune_JTuner
 * Method:    divGlobalSize
 * Signature: (I[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_jcltune_JTuner_divGlobalSize
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     ca_uwaterloo_jcltune_JTuner
 * Method:    mulLocalSize
 * Signature: (I[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_jcltune_JTuner_mulLocalSize
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     ca_uwaterloo_jcltune_JTuner
 * Method:    divLocalSize
 * Signature: (I[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_jcltune_JTuner_divLocalSize
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     ca_uwaterloo_jcltune_JTuner
 * Method:    addConstraint
 * Signature: (ILjava/util/function/Function;Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_jcltune_JTuner_addConstraint
  (JNIEnv *, jobject, jint, jobject, jobject);

/*
 * Class:     ca_uwaterloo_jcltune_JTuner
 * Method:    setLocalMemoryUsage
 * Signature: (ILjava/util/function/Function;Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_jcltune_JTuner_setLocalMemoryUsage
  (JNIEnv *, jobject, jint, jobject, jobject);

/*
 * Class:     ca_uwaterloo_jcltune_JTuner
 * Method:    addArgumentInput
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_jcltune_JTuner_addArgumentInput
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ca_uwaterloo_jcltune_JTuner
 * Method:    addArgumentOutput
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_jcltune_JTuner_addArgumentOutput
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ca_uwaterloo_jcltune_JTuner
 * Method:    addArgumentScalar
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_jcltune_JTuner_addArgumentScalar
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ca_uwaterloo_jcltune_JTuner
 * Method:    useFullSearch
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_jcltune_JTuner_useFullSearch
  (JNIEnv *, jobject);

/*
 * Class:     ca_uwaterloo_jcltune_JTuner
 * Method:    useRandomSearch
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_jcltune_JTuner_useRandomSearch
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     ca_uwaterloo_jcltune_JTuner
 * Method:    useAnnealing
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_jcltune_JTuner_useAnnealing
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     ca_uwaterloo_jcltune_JTuner
 * Method:    usePSO
 * Signature: (DIDDD)V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_jcltune_JTuner_usePSO
  (JNIEnv *, jobject, jdouble, jint, jdouble, jdouble, jdouble);

/*
 * Class:     ca_uwaterloo_jcltune_JTuner
 * Method:    outputSearchLog
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_jcltune_JTuner_outputSearchLog
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ca_uwaterloo_jcltune_JTuner
 * Method:    tune
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_jcltune_JTuner_tune
  (JNIEnv *, jobject);

/*
 * Class:     ca_uwaterloo_jcltune_JTuner
 * Method:    printToScreen
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ca_uwaterloo_jcltune_JTuner_printToScreen
  (JNIEnv *, jobject);

/*
 * Class:     ca_uwaterloo_jcltune_JTuner
 * Method:    printFormatted
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_jcltune_JTuner_printFormatted
  (JNIEnv *, jobject);

/*
 * Class:     ca_uwaterloo_jcltune_JTuner
 * Method:    printJSON
 * Signature: (Ljava/lang/String;Ljava/util/Map;)V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_jcltune_JTuner_printJSON
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     ca_uwaterloo_jcltune_JTuner
 * Method:    printToFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_jcltune_JTuner_printToFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ca_uwaterloo_jcltune_JTuner
 * Method:    suppressOutput
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_uwaterloo_jcltune_JTuner_suppressOutput
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
